### ISSUE TITLE
Figure out pinned content plan for homepage 

### ISSUE THREAD

**Issue by sinker** [mozilla/mozilla-opennews#170]

**Comment by sinker** [comment]
So we are adding blog posts to the homepage. We also may have more evergreen stuff we want "pinned" to the top. 

So a few questions:

1) Do we want to run the *full* blogpost on the home page? Or just excerpt with a "read more" (that's how it's set up right now).

2) If we are "pinning" to the top, we can do that either by hard-coding it in (easy), or by assigning a "pinned" variable to a blog post. That is the more elegant way of doing it, but requires some discipline, and also assumes that blog posts are the kind of thing that we'd be "pinning" vs links to pages like the fellows page etc.

3) either hard-coding or assigning a "pin" variable, we want a schedule and/or plan for refreshing this content. We are terrible at that now.

**Comment by kissane** [comment]
Yup.

1) Excerpt and "read more," please.

2) We want the pinned variable, but we don't have to do it that way *now*. We can always write a post for things we want to pin, and that can be our convention.

3) Yup. That's coming as soon as the refresh goes up, while it's all still fresh in my head. I've been making notes along the way.

**Comment by sinker** [comment]
OK awesome. I would say that for now, since it's the fellows box we want "pinned" we go with hard-code right now, just for simplicity's sake.

@kissane your temped-in version, you had some obvious fake blog posts, but then at the bottom you had this: https://github.com/mozilla/mozilla-opennews/blob/master/index.html#L30

Was that something we want just always on the home page? If so, should we format it differently? 

Also, should we call out the blog posts as such? "Updates from the OpenNews Blog" or "Latest News" or ??

**Comment by kissane** [comment]
Yeah, that About Us bit at the bottom should be somewhere on the page, but probably set off from the blog posts.

And yes, I think "Latest Updates" is a fine header for the blog posts, and was going to ask for that buuuuuut I forgot.

**Comment by kissane** [comment]
I tweaked the subheads on this page also. Going into the next PR.

**Comment by sinker** [comment]
closing this, addressed by a few different PRs
