### ISSUE TITLE
Plan and assign launch blog post

### ISSUE THREAD

**Issue by sinker** [mozilla/mozilla-opennews#172]

**Comment by kissane** [comment]
Can this just be a post from me saying we've re-orged the site and have a blog now?

**Comment by sinker** [comment]
Yes, I think that's exactly it.

**Comment by kissane** [comment]
OK, I'm going to leave this open till it's written

**Comment by sinker** [comment]
yup. I can't assigned this to you. But we could assign it to you.

**Comment by kissane** [comment]
wait whyyyy can't I have the assignment here, do I need to flip a switch somewhere?

**Comment by sinker** [comment]
YOU ARE ASSSSIGGNGNNGEEEDDDDD

**Comment by kissane** [comment]
O THANK GOD
