### ISSUE TITLE
Get full-res photos of fellows from LA

### ISSUE THREAD

**Issue by sinker** [mozilla/mozilla-opennews#173]

**Comment by sinker** [comment]
full-rez available here: https://www.dropbox.com/home/Public/onboarding%20photos

Will add to this as I grab headshots, so will leave issue open for now.

**Comment by kissane** [comment]
@sinker: That Dropbox URL is broken—I think that's the one you see, but I need the sharing URL

**Comment by sinker** [comment]
@kissane I *think* I just shared a folder with you, but jesus christ the dropbox folder sharing is some shittttty UX

**Comment by kissane** [comment]
Got it
