### ISSUE TITLE
Move featured sidebar content to top

### ISSUE THREAD

**Issue by sinker** [mozilla/mozilla-opennews#177]
@kissane I am not sure what this means

**Comment by kissane** [comment]
This module: ![screen shot 2015-01-14 at 2 31 27 pm](https://cloud.githubusercontent.com/assets/1910034/5745924/0b8db486-9bfa-11e4-8e8f-e3790d2bec1e.png)

**Comment by kissane** [comment]
I assume that's hard-coded somewhere?

**Comment by sinker** [comment]
Yes, it's here: https://github.com/mozilla/mozilla-opennews/blob/master/_includes/sidebar_update.html#L18

Are you saying this should be above the (soon-to-be-updated) OpenNews Projects menu?

**Comment by kissane** [comment]
I *think* it should be, because otherwise it's going to get lost—that programs menu is long. What do you think?

**Comment by sinker** [comment]
let's switch it and see. I'll do it with the next bunch of stuff.

**Comment by sinker** [comment]
@kissane I switched it. give a look on staging.

**Comment by kissane** [comment]
@sinker: Hmm. We should exclude it entirely on the homepage, either way, if we can. Otherwise, I'm not sure. Do you think it has more utility than the extra Programs menu?

**Comment by sinker** [comment]
I'm really unsure. it's such a BIG BLOCK that it's hard to know where its best placement is.

**Comment by sinker** [comment]
OK, staging now has a version where the fellowship block only appears on pages that are not the main landing page. play around with that and feel how it fits.

At least on my monitor, I feel like the fellows block text should be shorter.

**Comment by kissane** [comment]
OK, this is really useful. Yeah, it should be shorter. I'ma send a PR.

**Comment by sinker** [comment]
Yep, accepted PR and merged into #193
