### ISSUE TITLE
Tweak spacing between lead (big) and subsequent paragraphs 

### ISSUE THREAD

**Issue by sinker** [mozilla/mozilla-opennews#179]
we should also play around with :nth-child on this instead of the p class=bodybig

**Comment by kissane** [comment]
Yep

**Comment by sinker** [comment]
couple questions on this:

1) do you thtink the spacing is too *big* or *small* in terms of the tweaking?

2) do we want this convention on blog posts, or just on bigger intro pages or ???

**Comment by kissane** [comment]
Currently it's too big, I think. It's not a huge adjustment, but rn it's breaking the visual rhythm pretty hard. 
![screen shot 2015-01-14 at 2 40 59 pm](https://cloud.githubusercontent.com/assets/1910034/5746104/7049c468-9bfb-11e4-81a8-047293d2c809.png)

**Comment by sinker** [comment]
I brought this down by 15px in #192
