### ISSUE TITLE
titles are on top now?

### ISSUE THREAD

**Issue by sinker** [mozilla/mozilla-opennews#180]
@kissane I've noticed that you've moved titles to pages *above* images on some pages where that was not previously the case. Is that intentional? I can simplify that if so, because right now we have post_notitle for pages with images vs normal post pages. could stop calling the _notitle template if so.

**Comment by kissane** [comment]
@sinker: They're currently wildly inconsistent. I think this is a visual design call, so LMK what you think is best and I'll go through and standardize it.

**Comment by sinker** [comment]
my preference is the title below an image because title > BIG IMAGE > text feels weird to me

**Comment by kissane** [comment]
OK, I'll change that where they're the other way now

**Comment by kissane** [comment]
Done, will close after confirming once the PR works

**Comment by sinker** [comment]
yep, all done (and boy Github loved that merge for some reason). closing.
