### ISSUE TITLE
site footer content

### ISSUE THREAD

**Issue by erikao** [mozilla/mozilla-opennews#194]
currently:
    Get the latest by subscribing to our news feed
    Connect on Twitter @opennews
    Check our our Wiki
    Join our mailing list
    Contact us

Questions:
remove the wiki listing?
which email list should we be pointing people to? 
which contact us email? probably info@opennews.org

**Comment by sinker** [comment]
I removed the wiki listing in #196 and added a CC license button to the bottom of the stack.

**Comment by sinker** [comment]
agreed on info@opennews.org and will update accordingly.

**Comment by sinker** [comment]
OK, patched by #200 closing.
