### ISSUE TITLE
sidebar capitalization

### ISSUE THREAD

**Issue by erikao** [mozilla/mozilla-opennews#197]
Can we title case the program entries?That seems consistent with our subhead capitalization. The all lowercase just seems jarring compared to Source, MozFest, and the general site style (aside from the top menu items).

**Comment by sinker** [comment]
yes. will do.

**Comment by sinker** [comment]
OK, this is done. However it makes "fellowship partner guidelines" drop to two lines which is sub-optimal. @erikao or @kissane: is there a shorter name for that?

**Comment by kissane** [comment]
@sinker @erikao: News Partner Guidelines or Fellowship Partner Info?

**Comment by sinker** [comment]
I like Fellowship Partner Info.

**Comment by erikao** [comment]
agreed on Fellowship Partner Info.

That's also a good remidner that we also need to get better at using the phrase "fellowship partner" when we mean that and not "news partner" which is broader.

**Comment by kissane** [comment]
It's going to be Partner Info because that's all that fits across the top fellowship nav.

**Comment by kissane** [comment]
Haha. Didn't mean to close this. Will leave it open for review.

**Comment by sinker** [comment]
OK, sidebar has been updated in #212
