### ISSUE TITLE
adding the new opennews blog feed to planet.opennews

### ISSUE THREAD

**Issue by sinker** [mozilla/mozilla-opennews#198]
when we launch the blog, there will be a feed for it available at: opennews.org/feed.xml 

the actual <head> feed for the site is pointing to planet, NOT to this feed.

My inclination is that we keep the feed in <head> pointing to planet and we use this feed as a source for planet

so two questions here:

1) do we keep the <head> feed as planet and
2) how do we add this feed to planet?

**Comment by erikao** [comment]
Not sure on question 1.
On 2, here's the link for updating planet: https://docs.google.com/spreadsheets/d/12pZLK61z3X01sJ9tURhYSIm7EPHYocR4RX7LR_-CLwE/edit#gid=0

**Comment by sinker** [comment]
OK, I think then question 1 is leave it as-is. It seems weird to point to a partial feed when we have all our fellows etc.

Q 2 is fantastic. Out of fear of killing it throwing a non-existant feed right now, I will add it later but will leave this open so I have the link.

**Comment by sinker** [comment]
OK, I just added http://opennews.org/feed.xml to the google doc. Closing.
