### ISSUE TITLE
301-palooza

### ISSUE THREAD

**Issue by sinker** [mozilla/mozilla-opennews#201]
opening this issue to loop @jdotpz in. We need to collect a list of AALLLLLLL the pages that are changing location and ALLLLLLL the new pages that replace them.

JP, how would you like that information delivered?

**Comment by jdotpz** [comment]
Morse code would be fine.  If you don't know morse that well, you can feel free to put it in this issue and let me know when.
We should set this site up on Cloudfront one day.

**Comment by sinker** [comment]
it's going to essentially be every page on the site. does a spreadsheet make more sense or ??? and it'll be probably tomorrow by EOD.

**Comment by kissane** [comment]
Here's where we're at now:

http://opennews.org/fellowships/ -> http://opennews.org/what/fellowships/
http://opennews.org/fellowships/info.html -> http://opennews.org/what/fellowships/info.html
http://opennews.org/fellowships/community.html -> http://opennews.org/what/fellowships/community.html
http://opennews.org/fellowships/faq.html -> http://opennews.org/what/fellowships/faq.html
http://opennews.org/hackdays.html -> http://opennews.org/what/community/eventsupport.html
http://opennews.org/code.html -> http://opennews.org/what/community/eventsupport.html
http://opennews.org/source.html -> http://opennews.org/what/community/source.html
http://opennews.org/srccon.html -> http://opennews.org/what/conferences/srccon.html
http://opennews.org/newspartners.html -> http://opennews.org/getinvolved/newspartners.html
http://opennews.org/partnerguidelines.html -> http://opennews.org/what/fellowships/partnerguidelines.html
http://opennews.org/getinvolved.html -> http://opennews.org/getinvolved/

**Comment by sinker** [comment]
just a note that these may change significantly before the end of the night.

**Comment by jdotpz** [comment]
I'll count on it!  Tomorrow, we'll setup the redirects on staging to test,
and then just search/replace the domain names.

**Comment by sinker** [comment]
OK, I did a big move and now we no longer have .html after all our pages (see #226) as a result, the pages listed above are incorrect. I made a spreadsheet:

https://docs.google.com/spreadsheets/d/19-HqXTPe3nqDBWxVv5P-FSkwuQScsK3fZdpVomXn5Us/edit?usp=sharing

**Comment by jdotpz** [comment]
Alright I'll get cooking here.

**Comment by jdotpz** [comment]
OK, all the redirects are up.  For future JP who wants to know what I did:

<RoutingRules>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>fellowships/info.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <Protocol>http</Protocol>
            <HostName>opennews.org</HostName>
            <ReplaceKeyPrefixWith>what/fellowships/info/</ReplaceKeyPrefixWith>
            <HttpRedirectCode>302</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>fellowships/community.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <Protocol>http</Protocol>
            <HostName>opennews.org</HostName>
            <ReplaceKeyPrefixWith>what/fellowships/community/</ReplaceKeyPrefixWith>
            <HttpRedirectCode>302</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>fellowships/faq.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <Protocol>http</Protocol>
            <HostName>opennews.org</HostName>
            <ReplaceKeyPrefixWith>what/fellowships/faq/</ReplaceKeyPrefixWith>
            <HttpRedirectCode>302</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>fellowships/apply.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <Protocol>http</Protocol>
            <HostName>opennews.org</HostName>
            <ReplaceKeyPrefixWith>what/fellowships/apply/</ReplaceKeyPrefixWith>
            <HttpRedirectCode>302</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>fellowships/2015meet.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <Protocol>http</Protocol>
            <HostName>opennews.org</HostName>
            <ReplaceKeyPrefixWith>what/fellowships/2015meet/</ReplaceKeyPrefixWith>
            <HttpRedirectCode>302</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>fellowships/2014meet.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <Protocol>http</Protocol>
            <HostName>opennews.org</HostName>
            <ReplaceKeyPrefixWith>what/fellowships/2014meet/</ReplaceKeyPrefixWith>
            <HttpRedirectCode>302</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>fellowships/2013meet.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <Protocol>http</Protocol>
            <HostName>opennews.org</HostName>
            <ReplaceKeyPrefixWith>what/fellowships/2013meet/</ReplaceKeyPrefixWith>
            <HttpRedirectCode>302</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>fellowships/2012meet.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <Protocol>http</Protocol>
            <HostName>opennews.org</HostName>
            <ReplaceKeyPrefixWith>what/fellowships/2012meet/</ReplaceKeyPrefixWith>
            <HttpRedirectCode>302</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>fellowships/2011meet.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <Protocol>http</Protocol>
            <HostName>opennews.org</HostName>
            <ReplaceKeyPrefixWith>what/fellowships/2011meet/</ReplaceKeyPrefixWith>
            <HttpRedirectCode>302</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>fellowships/</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <Protocol>http</Protocol>
            <HostName>opennews.org</HostName>
            <ReplaceKeyPrefixWith>what/fellowships/</ReplaceKeyPrefixWith>
            <HttpRedirectCode>302</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>hackdays.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <Protocol>http</Protocol>
            <HostName>opennews.org</HostName>
            <ReplaceKeyPrefixWith>what/community/eventsupport</ReplaceKeyPrefixWith>
            <HttpRedirectCode>302</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>code.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <Protocol>http</Protocol>
            <HostName>opennews.org</HostName>
            <ReplaceKeyPrefixWith>what/community/eventsupport</ReplaceKeyPrefixWith>
            <HttpRedirectCode>302</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>source.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <Protocol>http</Protocol>
            <HostName>opennews.org</HostName>
            <ReplaceKeyPrefixWith>what/community/source</ReplaceKeyPrefixWith>
            <HttpRedirectCode>302</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>srccon.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <Protocol>http</Protocol>
            <HostName>opennews.org</HostName>
            <ReplaceKeyPrefixWith>what/conferences/srccon</ReplaceKeyPrefixWith>
            <HttpRedirectCode>302</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>newspartners.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <Protocol>http</Protocol>
            <HostName>opennews.org</HostName>
            <ReplaceKeyPrefixWith>getinvolved/newspartners</ReplaceKeyPrefixWith>
            <HttpRedirectCode>302</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>getinvolved.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <Protocol>http</Protocol>
            <HostName>opennews.org</HostName>
            <ReplaceKeyPrefixWith>getinvolved</ReplaceKeyPrefixWith>
            <HttpRedirectCode>302</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>partnerguidelines.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <Protocol>http</Protocol>
            <HostName>opennews.org</HostName>
            <ReplaceKeyPrefixWith>what/fellowships/partnerguidelines</ReplaceKeyPrefixWith>
            <HttpRedirectCode>302</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
</RoutingRules>
