### ISSUE TITLE
need team eyes/blessing on new opennews blurb

### ISSUE THREAD

**Issue by kissane** [mozilla/mozilla-opennews#203]
This is now at the top of the homepage, so I want to explicitly request a team review on it:

> OpenNews is a joint project of Mozilla and the Knight Foundation dedicated to helping journalism thrive on the open web by supporting the international community of developers, designers, and data journalists in newsrooms.

Note: I'm using "joint project" instead of "partnership" because although the latter is accurate, it's a weird as the main noun defining OpenNews.

**Comment by erikao** [comment]
questions that jump out at me:

international (as a defining part of the program description) y/n?

and, newsrooms seems a little narrow. possible edits:
* in journalism (though that says journalism twice in one sentence)
* in and around journalism (clunky)

**Comment by kissane** [comment]
> OpenNews is a joint project of Mozilla and the Knight Foundation dedicated to helping journalism thrive on the open web by supporting the community of developers, designers, and data journalists in and around newsrooms.

?

**Comment by ryanpitts** [comment]
how about just <s>in and around newsrooms</s>

**Comment by ryanpitts** [comment]
"OpenNews is a joint project of Mozilla and the Knight Foundation that helps journalism thrive on the open web by supporting the community of developers, designers, and data journalists."

**Comment by sinker** [comment]
OpenNews is a joint project of Mozilla and the Knight Foundation that helps journalism thrive on the open web by supporting the _vibrant_ community of developers, designers, and data journalists.

or some other adjective 

?

**Comment by ryanpitts** [comment]
"growing" maybe feels like the expected word, but it is also a true word

**Comment by kissane** [comment]
I will admit that I added and then removed "vibrant" days ago because it felt a little copywriting-y. "Growing" seems accurate and good, if expected.

It's a little conceptually weird to not have anything after "developers, designers, and data journalists" though, right? Because we're not supporting *all* developers and designers. I mean, no one will be confused, but if this is gonna be front and center, I want to make it as watertight as possible.

What about:

> OpenNews is a joint project of Mozilla and the Knight Foundation that helps journalism thrive on the open web by supporting the vibrant community of news developers and data journalists.

**Comment by ryanpitts** [comment]
I like how tight that is. I still think "vibrant" maybe sounds copywrite-y though :/

**Comment by sinker** [comment]
I'm OK with "growing"

**Comment by erikao** [comment]
i also like how tight that is, but...
do we care about 
losing designer as a separate group from developer?
AND
the fact that data journalist is super broad and can mean excel driven reporting?

**Comment by kissane** [comment]
Oh god, "vibrant" was all cold pills, I meant to write "growing."

We don't really talk much about designers on the site now, so IDK—I liked having it in, but I dunno if I care about losing it. I feel more strongly that it's cool to go big-tent with the data journalists, since a ton of the Source Learning stuff is super helpful for even the CAR-iest people.

**Comment by kissane** [comment]
More:

> OpenNews is a joint project of Mozilla and the Knight Foundation that helps journalism thrive on the open web by supporting the growing community of news developers, designers, and data-wranglers.

or 

> OpenNews is a joint project of Mozilla and the Knight Foundation that helps journalism thrive on the open web by supporting developers, designers, and data nerds in and around newsrooms.

**Comment by sinker** [comment]
I like the "growing community" version, will integrate.

**Comment by sinker** [comment]
this is blessed and added in #223. closing.
