### ISSUE TITLE
fellows content block in sidebar format is weird

### ISSUE THREAD

**Issue by kissane** [mozilla/mozilla-opennews#205]
![screen shot 2015-01-15 at 1 28 34 pm](https://cloud.githubusercontent.com/assets/1910034/5763689/9ab4148c-9cba-11e4-81ac-73b96f84b7d6.png)

The link is in the same graf as the other text, but it's rendering with a line break, which makes me think there's a style somewhere rendering links here as block elements. @sinker?

**Comment by sinker** [comment]
Yep, that was the problem. I will also fix the link issue that @erikao caught.

**Comment by sinker** [comment]
OK, these two issues are fixed in #209
