### ISSUE TITLE
info@opennews.org email 

### ISSUE THREAD

**Issue by erikao** [mozilla/mozilla-opennews#206]
Hey JP, I think you originally got us set up with this. It seems it may have gotten borked in the email migration. Can you help us find out who is now getting these emails? Prior to the email migration, it was set up to email all of us--me, Dan, Erin, and Ryan. I think we also had a srccon@opennews.org and maybe also a source@opennews.org email set up. 

Thanks for any info on this.

**Comment by jdotpz** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1122202
Checking!

**Comment by erikao** [comment]
looks like we're all set up! thanks, JP.
