### ISSUE TITLE
change "All our Programs" name?

### ISSUE THREAD

**Issue by sinker** [mozilla/mozilla-opennews#207]
So thinking about the sidebar nav, do we want that top heading to be a litlte more active, like "Learn More About"

**Comment by kissane** [comment]
I went boring because I wanted it to be super clear what people were looking at, BUT maybe we do what you've suggested and add the Get Involved page and just have it be a dupe nav.

**Comment by sinker** [comment]
it feels like a prompt vs a "here's a list" is important. Here's what it would look like. 
![learnmoreabout](https://cloud.githubusercontent.com/assets/361410/5764347/1e70893c-9ca6-11e4-98c2-09fb88c31f6f.jpg)

**Comment by erikao** [comment]
i like the "learn more about" or, does it look super weird to have no heading ahead of the headings?

**Comment by sinker** [comment]
hrm?

**Comment by erikao** [comment]
the overall heading before you get to each of the sublists seems like it could just be removed. or maybe if it's there, it should have different styling than each subgroup. cause right now "all our programs" just seems a little superfluous.

**Comment by sinker** [comment]
yeah, I'd kill "all our programs" and JUST go with "learn more about..."  like the graphic above.

**Comment by kissane** [comment]
:+1:

**Comment by sinker** [comment]
OK, this is updated in #209
