### ISSUE TITLE
fellowship partner info page

### ISSUE THREAD

**Issue by erikao** [mozilla/mozilla-opennews#210]
some updates:
* title should reflect title in issue #197 
concluding paragraph:
If you have any questions about becoming a fellowship partner for 2016, [mailto: info@opennews.org please contact us]. In the spring of 2015, we'll update this page with details about the application process to become a fellowship partner. And if being a fellowship partner doesn’t sound like a fit for your news organization next year, please check out the many other ways we [/getinvolved/newspartners.html partner with newsrooms].

(Exact wording up for editing, mostly just want to remove the form. We may update the form and I don't think we want to be on the hook for monitoring responses outside of the application period.)

**Comment by kissane** [comment]
Done and in the next PR.

**Comment by sinker** [comment]
closed with #221
