### ISSUE TITLE
srccon info page

### ISSUE THREAD

**Issue by erikao** [mozilla/mozilla-opennews#211]
* link in first paragraph "the inaugural srccon" should be to srccon site (currently links to the page we are on)
* in the final paragraph, need to link to the SRCCON emai list, which I think is this link? https://source.opennews.org/en-US/subscribe/ (I don't know what the URL for the email subscription directly would be, but if there's a URL that doesn't take you to a different website, that seems great)

Nice to haves
* links to blog posts related to SRCCON
* maybe a little blurb about when we expect to share info about SRCCON 2015?

**Comment by sinker** [comment]
I'm going to leave the "nice to haves" for a later date.

**Comment by kissane** [comment]
Got the first two points. Going into the next PR.

**Comment by sinker** [comment]
closed with #221
