### ISSUE TITLE
mozfest info page

### ISSUE THREAD

**Issue by erikao** [mozilla/mozilla-opennews#213]
needs a link to announcement list
could make match issue #211 OR link to the mojo page: https://lists.mozilla.org/listinfo/community-mojo

I'm stumbling over this sentence a little:
"Join us in discussions, hands-on making, and wireframing, and help explore new ways to visualize data, present information, and foster connections between people interested in harnessing the power of the web to create great journalism."

Maybe "MozFest is a place for discussions, hands-on making, and wireframing. It's a chance to explore new ways to visualize data, present information, and foster connections between people interested in harnessing the power of the web to create great journalism."

**Comment by sinker** [comment]
Does anyone object to retitling this page "Journalism at the Mozilla Festival"? and losing the Source Code bit??

**Comment by sinker** [comment]
I would opt towards pushing people to the Source list, same as #211 @kissane do you have feels?

**Comment by kissane** [comment]
Ha, yeah, that copy is rough. I forget where it came from. Edited, and retitled, and Source announcements list linked. Going in the next PR.

**Comment by sinker** [comment]
closed with #221
