### ISSUE TITLE
code and community support landing page

### ISSUE THREAD

**Issue by erikao** [mozilla/mozilla-opennews#214]
* the intro block is LONG. can we break up into two sections?
* Also, maybe it's possible to shorten this:
"The developers, journalists, and data wranglers who make up the news code community work in newsrooms (and affiliated organizations) around the world, shipping interactive features, code libraries, and support systems at newsroom pace: fast."

like, either give the list of people and that they work at newsroom pace: fast OR say "the news code community" and list the types of work. basically, it seems like we don't need to list both the people and the things they do, but listing either or would give the same information and make this a snappier opening.
also, maybe we can pull the shorthand for the community from whatever we decide from #203

* link up Source Jobs in the Source blurb
* in the event sponsorship section the final link should be to the sponsorship page directly: /what/community/eventsupport.html
* maybe also rename the event sponsorship to event support so it matches the menu item?

**Comment by kissane** [comment]
Done and done. Going in the next PR.

**Comment by sinker** [comment]
closed with #221
