### ISSUE TITLE
text formatting -- code convening page

### ISSUE THREAD

**Issue by erikao** [mozilla/mozilla-opennews#216]
going to start listing pages that just need help with how text is rendering

* the code convening example block looks a little weird, I think cause the list has slightly different styling than paragraph blocks.

**Comment by kissane** [comment]
Fixed, going in next PR

**Comment by sinker** [comment]
fixed by #221 but I may tweak the list CSS further, so leaving open.

**Comment by sinker** [comment]
closed by #224
