### ISSUE TITLE
giant fellowship photo looks a little crazy on the WHO page

### ISSUE THREAD

**Issue by sinker** [mozilla/mozilla-opennews#217]
It's super enormous and a little jarring. Not sure what graphic we could use in its place on that page tho. However, it is a hell of a graphic that we should use somewhere.

**Comment by ryanpitts** [comment]
Dropping the graphic right below the fellows paragraph mitigates a little bit, I think.

![screen shot 2015-01-15 at 12 41 02 pm](https://cloud.githubusercontent.com/assets/56477/5766123/daf52556-9cb3-11e4-9f51-06ac16a44b07.png)

There are 26 mug shots, so another option is to go back to original graphic, shrink the photos slightly and do 3 rows of 9 photos (with one empty slot somewhere getting the dots).

**Comment by kissane** [comment]
Did you intentionally arrange them from far away heads to big/close up? Because now that I've seen it I can't unseeeee

**Comment by kissane** [comment]
And that array should go in /what/fellowships/community.html, IMO

**Comment by sinker** [comment]
yes to that array in what/fellows/community. will move and tweak accordingly.

**Comment by sinker** [comment]
made the switch with #223 closing
