### ISSUE TITLE
community calls page

### ISSUE THREAD

**Issue by erikao** [mozilla/mozilla-opennews#218]
Question -- is this meant to replace the wiki page for calls?

* updates to second paragraph:
"You can participate by calling in and listening, reading along on the etherpad during or after the call, or by [mailto: erika@mozillafoundation.org contacting us] to get onto the agenda as a speaker—the calls are informal and friendly and a great way to ease into the wider conversation."

If this is replacing the wiki, we can remove the link to the wiki. Could replace it with: etherpad for next call: next call, January 21: https://etherpad.mozilla.org/opennews-calls-Jan21

and we should add two more etherpads:
December 10, 2014: https://etherpad.mozilla.org/opennews-calls-Dec10
January 7, 2015: https://etherpad.mozilla.org/opennews-calls-Jan7

**Comment by kissane** [comment]
It's meant to replace the wiki for now. Dunno about the future. Changes made, will be in my next PR.

**Comment by sinker** [comment]
changes made in  #221 

How do people feel about having a jquery rolldown thing on the gigantic call list?

**Comment by erikao** [comment]
Oh, yeah, whatever makes sense. I just kept up with the list cause it
existed, but i dunno that a page needs a huuuuuuge list like that.

**Comment by sinker** [comment]
could make it so it only displays the first five, then a rolldown for alllllllllll the rest

**Comment by sinker** [comment]
made a very simple trigger to show more than the last five calls. added into master with #223. closing.
