### ISSUE TITLE
event support

### ISSUE THREAD

**Issue by erikao** [mozilla/mozilla-opennews#219]
* does this replace the hackdays page? if no, how are they different?
* if it replaces, remove the hackdays link in the first line.
* if it replaces, we may need to move over the tabletop code block so we can list events, or just deprecate that since the events have become far less frequent.
* if it replaces, we should just link to the Source events listing somewhere in here too. Easiest place might be an addtional line in the second paragraph.
* if based on issue #218 we're deprecating call wiki, we should switch community call link to /what/community/calls.html
* in the list of projects, Treasury.io is listed twice, remove the second listing

**Comment by kissane** [comment]
It does replace the hackdays page, and all these notes are good. I will make the changes and report back. In awhile.

**Comment by kissane** [comment]
I didn't move the Tabletop code, but we may want to later on. Also, I dunno what to do with the wiki and that is a larger conversation, so I've switched in the new link for now and we can deal with that later.

All other changes are made in my fork and will be coming soon to a PR.

**Comment by sinker** [comment]
all changes addressed in #221 

I am leaving this open and will migrate the tabletop code.

**Comment by sinker** [comment]
done in #223 closing.
