### ISSUE TITLE
/what/fellowships/why.html is missing

### ISSUE THREAD

**Issue by sinker** [mozilla/mozilla-opennews#222]
not such which page is supposed to be why.html but currently it is nonexistant and breaks the fellowship menu as a result. @kissane any guidance?

**Comment by erikao** [comment]
we could comment that out of the menu till application time.

**Comment by sinker** [comment]
yep, definitely. just double-checking that it doesn't exist as a page right now and just has a different name.

**Comment by kissane** [comment]
Sorry, that was actually meant to be commented out till we start the next round of fellowship outreach.

**Comment by sinker** [comment]
done in #223 closed.
