### ISSUE TITLE
Our blurb got us through launch, but…

### ISSUE THREAD

**Issue by kissane** [mozilla/mozilla-opennews#233]
I am not in love with it. Here's the existing one, and I'll work on revisions this week:

> OpenNews is a joint project of Mozilla and the Knight Foundation that helps journalism thrive on the open web by supporting the growing community of news developers, designers, and data-wranglers.

**Comment by kissane** [comment]
OpenNews is a joint project of Mozilla and the Knight Foundation that supports the growing community of news developers, designers, and data nerds helping journalism thrive on the open web.

**Comment by sinker** [comment]
I like that better, plus is shorter.

**Comment by kissane** [comment]
OpenNews is a joint project of Mozilla and the Knight Foundation that supports the growing community of news developers, designers, and data reporters helping journalism thrive on the open web.

**Comment by ryanpitts** [comment]
:+1:
