### ISSUE TITLE
Fellowship partner guidlines update

### ISSUE THREAD

**Issue by erikao** [mozilla/mozilla-opennews#245]
Placeholder for text updates to: http://opennews.org/what/fellowships/partnerguidelines/

to include a big call out for people to sign up to hear when the application has been posted and the application timeline details.

**Comment by erikao** [comment]
in big text underneath the first paragraph on the page:
From April 1 to April 24 we will accept applications from news organizations interested in hosting a fellow in 2016. Please [sign up to receive an email] when we launch the application.

In the paragraph after the bulleted list:
If you have are interested in becoming a fellowship partner in 2016, [add your details to this list] so we can email you when the application is available. We'll accept applications from news organizations from April 1-24, review the applications and interview candidates in May, and announce the 2016 cohort of fellowship partners in early June. If being a fellowship partner doesn’t sound like a fit for your organization, check out the many other ways we [work with newsrooms](/getinvolved/newspartners).

For the signup form:
[A quick google form]
Name
News organization
Email address
What interests you in the Knight-Mozilla Fellowship?
[thank you page that reiterates we will email the full application on April 1]

**Comment by sinker** [comment]
#249 brings this into staging: http://opennews.mofostaging.net/what/fellowships/partnerguidelines/

**Comment by sinker** [comment]
closed by #249
