### ISSUE TITLE
rss feed is messing up opennews's internal blog URL

### ISSUE THREAD

**Issue by sinker** [mozilla/mozilla-opennews#258]
manifesting as http://opennews.org/blog/blog/post instead of opennews.org/blog/post

**Comment by ryanpitts** [comment]
Looks like it's just because "/blog" appears in `permalink` as well as `url` in _config.yml. Then the [feed template smushes them together](https://github.com/mozilla/mozilla-opennews/blob/master/feed.xml#L21-L22).
