### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by coboje** [mozilla/mozilla-opennews#80]
This is a very nicely made site, and I would love to use it as a guide as I develop my own Jekyll site. What kind of license applies to this project? Would it be ok to fork and reuse parts of it?

**Comment by sinker** [comment]
Hey, I'm so sorry we never responded before now. Honestly, never noticed this issue was in here. But THANK YOU for submitting it!

We just added an MIT license to the project, and also CC/BY to the content on the site. Thanks for submitting and hope that this is perhaps still useful to you!
